version: '3.8'
services:
  backend:
    image: backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: desapegaadmin
      POSTGRES_PASSWORD: desapegasenha
      POSTGRES_DB: desapegadb
    ports:
      - "5434:5432" 