services:
  backend:
    build: ./backend
    image: desapega-backend:latest
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT:       "3000"
      DB_HOST:    db           
      DB_PORT:    "5432"      
      DB_USER:    desapegaadmin
      DB_PASSWORD: desapegasenha
      DB_NAME:    desapegadb
    env_file:
      - backend/.env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER:     desapegaadmin
      POSTGRES_PASSWORD: desapegasenha
      POSTGRES_DB:       desapegadb
    ports:
      - "5435:5432"       
